= Бізнес логіка СТЕКУ Програмного забеспечення
:toc:

== 1 Аналіз вимог та  планування.

1. Організувати легке розповсюдження програмних компонентів, спростити процесс встановлення ПЗ та організувати його роботу на найпопулярніших ОС. т.т. (Windows/Dos,Linux,Mac)

2. Враховуючи файли характеристики двигуна, користуємої операційної системи та налаштувань користувача, організувати роботу Supply Сhain-a та корректну роботу кожного компонента в схемі: Firmware, Bridge, Control Panel

3. Організувати зручний збір даних для зберігання інформації у файлах журналювання (logs), форма журналювання має бути зручним для парсування.

== 2 Дизайн системи

1. Дизайн системи розроблений за схемою послідовного Supply-Chain(у), та описаний у документі 
https://github.com/amuerta/SpecialArch/tree/docs/sw_arch/arch.adoc[Архітектура Стеку ПЗ]. Відповідно до нього реалізується увесь функціонал програмного забезпеченная з використанням мов програмування C та V.

2. Основними інструментами розробки слугуватиме:
 
  - st-link toolchain
  - neovim text editor
  - nonebi-arm-v8-gcc compiler
  - make
  - git with github.com as hosting
  - V language for software testing

== 3 Реалізація функцій

1. Програмне забезпечення Панелі Контролю реалізуватиме:

  - контроль потенційного двигуна
      . напрям обертання (за год. стрілкою чи проти)
      . кількість обертів за хв.
      . кількість mV подаваємих до двигуна
  - контроль вбудованого в мікросхему LED ліхтарика
      . запалити LED
      . сказати йому миготіти з заданою частотою (спалахів на хв.)
  - контроль міросхеми
      . обнулення стану мікросхеми

2. Програмне забезпечення "Мосту" реалізуватиме:

  - зчитування файлів інтерфейсу (вводу та виводу) (in/out)
  - парсування та лексування значень з файлів чи з мікросхеми, Серіалізація та Десеріалізація даних для можливості переводу сигналів у текстовий формат і навпаки.
  - Комунікація з мікросхемою через порт USB з використанням бібліотеки комунікації `libusb`

3. Програмне забезпечення "Прошивки" реалізуватиме:

  - можилвість отримання та відправки команд по стандарту описаному в https://github.com/amuerta/SpecialArch/tree/docs/sw_arch/arch.adoc[Архітектура Стеку ПЗ]
  - обробка та виконання команд на фізичній мікросхемі користуючись стандартною бібліотекою вводу та виводу на мікросхемах STM32 - GPIO.

== 4 Взаємодія з контроллером STM32F407VETx:

Взаємодія з контроллером виконується строго відповідно за https://github.com/amuerta/SpecialArch/tree/docs/sw_arch/arch.adoc[Архітектура Стеку ПЗ].

== 5 Розробка графічного інтерфесу.

Графічний інтерфейс виконаний за https://github.com/amuerta/SpecialArch/tree/docs/sw_arch/arch.adoc#приклад-макету-користувацького-інтерфесу[макетом користувацьокого інтерфейсу] з використанням бібліотеки https://www.raylib.com[Raylib] на мові програмування С.

Інтерфес стандартизовний у  https://github.com/amuerta/SpecialArch/blob/docs/sw_arch/arch.adoc#панель-керування[Архітектурі ПЗ]

== 6 Тестування

Тестування та налагодження відбувається з використанням Vlang скриптів, що розміщенні у Git гілці `tests`

Причиною вибору Vlang є те що:

- мова і її інтерпритатор та компілятор доступні на усіх популярних операційних системах: Windows, Linux, Mac, Android, BSD.

- мова дозволяє запуск source файлів як скрипти (Подібно до python).

- мова є ДУЖЕ швидкою, простою, легкою. Тому може розміщуватись безпосередньо у репозиторії проетку.

- мова є дуже зручною для написання тестів в міру значної реалізації функціоналу файлової системи, керування процессів, т.д.


Тести перевірятимуть на справність роботи кожний компонент окремо, після чого буде іти перевірка на їх співпрацю як єдиної системи.

Уцілому можна відмітити тести що будуть перевіряти:
  
- роботу прошивки
- роботу мосту
- роботу інтерфейсу
- співрацю:
    . прошивка <==> міст
    . міст <==> інтерфейс
- коректність форматування конфігураційних файлів.
- коректність форматування обох інтерфесів.
- стабільність системи корегування та https://en.wikipedia.org/wiki/Bounds_checking[цензури] інформації що забезпечує міст міє схемою та панелью керування. 

Тести можливо буде викликати для кожного компоненту індивідуально запустивши в директорії кожного програмного компоненту `make test`

== 7 Документація та звітність

Документація та звітність доступна на  https://github.com/amuerta/SpecialArch.git[Github Репозиторії] проекту, у гілці https://github.com/amuerta/SpecialArch/tree/docs[docs].

== 8 Навчання та підтримка

Проект розіщений під  https://en.wikipedia.org/wiki/WTFPL[WTFPL] ліцензією, що дозволяє публіці робити з копіями коду що заманеться.

Оригінальний проект може бути підтриманий будь ким https://github.com/amuerta/SpecialArch/pulls[тут]
